# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(577, 606)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 160, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(70, 310, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check.setFont(font)
        self.check.setObjectName("check")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(290, 310, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.change_session = QtWidgets.QPushButton(self.centralwidget)
        self.change_session.setGeometry(QtCore.QRect(70, 390, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.change_session.setFont(font)
        self.change_session.setObjectName("change_session")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Words_translation"))
        self.label.setText(_translate("MainWindow", "Words"))
        self.check.setText(_translate("MainWindow", "Проверить"))
        self.next.setText(_translate("MainWindow", "Дальше"))
        self.change_session.setText(_translate("MainWindow", "Новая сессия"))
